Task 1


In [1]:
def convert_units():
    """
    Converts between different units of measurement.

    Supported conversions:
    - Length: meters <-> feet
    - Weight: kilograms <-> pounds
    - Volume: liters <-> gallons

    Returns:
        float: converted value
    """

    try:
        print("Choose conversion type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = int(input("Enter choice (1-3): "))

        value = float(input("Enter value to convert: "))

        if choice == 1:
            print("1. meters -> feet")
            print("2. feet -> meters")
            option = int(input("Choose option: "))

            if option == 1:
                result = value * 3.28084
                print("Result:", result, "feet")
            elif option == 2:
                result = value / 3.28084
                print("Result:", result, "meters")

        elif choice == 2:
            print("1. kg -> pounds")
            print("2. pounds -> kg")
            option = int(input("Choose option: "))

            if option == 1:
                result = value * 2.20462
                print("Result:", result, "pounds")
            elif option == 2:
                result = value / 2.20462
                print("Result:", result, "kg")

        elif choice == 3:
            print("1. liters -> gallons")
            print("2. gallons -> liters")
            option = int(input("Choose option: "))

            if option == 1:
                result = value * 0.264172
                print("Result:", result, "gallons")
            elif option == 2:
                result = value / 0.264172
                print("Result:", result, "liters")

        else:
            print("Invalid conversion type")

    except ValueError:
        print("Invalid input. Please enter numeric values.")

In [2]:
convert_units()

Choose conversion type:
1. Length
2. Weight
3. Volume
1. meters -> feet
2. feet -> meters


Task 2

In [20]:
def find_sum(numbers):
    """
    Returns sum of numbers in a list.
    """
    return sum(numbers)

def find_average(numbers):
    """
    Returns average of numbers in a list.
    """
    return sum(numbers) / len(numbers)

def find_min(numbers):
    """
    Returns minimum number in list.
    """
    return min(numbers)

def find_max(numbers):
    """
    Returns maximum number in list.
    """
    return max(numbers)
try:
    operation = input("Choose operation (sum, avg, max, min): ")

    nums = list(map(float, input("Enter numbers separated by space: ").split()))

    if len(nums) == 0:
        raise ValueError("List is empty")

    if operation == "sum":
        print(find_sum(nums))

    elif operation == "avg":
        print(find_average(nums))

    elif operation == "max":
        print(find_max(nums))

    elif operation == "min":
        print(find_min(nums))

    else:
        print("Invalid operation")

except ValueError:
    print("Invalid input.")


12.0


Exercise on List Manipulation

In [4]:
my_list = [1, 2, 3, 4, 5, 6]
def extract_every_other(lst):
    """
    Returns every other element from list.
    """
    return lst[::2]
extract_every_other(my_list)

[1, 3, 5]

In [5]:
def get_sublist(lst, start, end):
    """
    Returns sublist from start to end (inclusive).
    """
    return lst[start:end+1]
get_sublist(my_list, 1, 4)

[2, 3, 4, 5]

In [6]:
def reverse_list(lst):
    """
    Returns reversed list using slicing.
    """
    return lst[::-1]
reverse_list(my_list)

[6, 5, 4, 3, 2, 1]

In [7]:
def remove_first_last(lst):
    """
    Removes first and last elements.
    """
    return lst[1:-1]
remove_first_last(my_list)

[2, 3, 4, 5]

In [8]:
def get_first_n(lst, n):
    """
    Returns first n elements.
    """
    return lst[:n]
get_first_n(my_list, 3)

[1, 2, 3]

In [9]:
def get_last_n(lst, n):
    """
    Returns last n elements.
    """
    return lst[-n:]
get_last_n(my_list, 3)

[4, 5, 6]

In [10]:
def reverse_skip(lst):
    """
    Returns elements starting from second-last
    in reverse order skipping one each time.
    """
    return lst[-2::-2]
reverse_skip([1,2,3,4,5,6])

[5, 3, 1]

Nested List Exercise 

In [11]:
def flatten(lst):
    """
    Flattens one level of nested list.
    """
    result = []
    for sub in lst:
        for item in sub:
            result.append(item)
    return result
flatten([[1, 2], [3, 4], [5, 6]])

[1, 2, 3, 4, 5, 6]

In [12]:
def access_nested_element(lst, indices):
    """
    Access element using index path.
    """
    element = lst
    for i in indices:
        element = element[i]
    return element
lst = [[1,2,3],[4,5,6],[7,8,9]]
access_nested_element(lst,[1,2])

6

In [13]:
def sum_nested(lst):
    """
    Returns sum of all numbers in nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total
lst = [1, [2, 3], 4, 5]
sum_nested(lst)

15

In [14]:
def remove_element(lst, elem):
    """
    Removes all occurrences of elem in nested list.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        else:
            if item != elem:
                result.append(item)

    return result
lst = [1, [2, 3], 4, 5, 2]
remove_element(lst, 2)

[1, [3], 4, 5]

In [15]:
def find_max(lst):
    """
    Returns maximum value in nested list.
    """
    maximum = float("-inf")

    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum, item)

    return maximum
lst = [1, [2, 3], 4, 5]
find_max(lst)

5

In [16]:
def count_occurrences(lst, elem):
    """
    Counts occurrences of element in nested list.
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1

    return count
lst = [1, [2, 3], 4, 5, 2]
count_occurrences(lst, 2)


2

In [17]:
def deep_flatten(lst):
    """
    Flattens nested list of any depth.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result
lst = [1, [2, [3, 4], 5], 6]
deep_flatten(lst)

[1, 2, 3, 4, 5, 6]

In [18]:
def average_nested(lst):
    """
    Returns average of nested list elements.
    """

    flat = deep_flatten(lst)

    return sum(flat) / len(flat)
lst = [1, [2, [3, 4], 5], 6]
average_nested(lst)

3.5

Numpy Tasks

In [1]:
import numpy as np 

Basic Vector and Matrix Operation with NumPy

In [2]:
arr1 = np.empty((2,2))
print(arr1)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.04078059e-311]]


In [3]:
arr2 = np.ones((4,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
arr3 = np.full((3,3), 7)
print(arr3)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [5]:
arr4 = np.zeros_like(arr3)
print(arr4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
arr5 = np.ones_like(arr3)
print(arr5)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
new_list = [1,2,3,4]

arr6 = np.array(new_list)

print(arr6)

[1 2 3 4]


Array Manipulation

In [8]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)

In [ ]:
identity = np.eye(3)
print(identity)

In [ ]:
rand_arr = np.random.random(30)

mean_val = rand_arr.mean()

print(rand_arr)
print("Mean:", mean_val)

In [ ]:
arr = np.random.random((10,10))

print("Min:", arr.min())
print("Max:", arr.max())

In [ ]:
arr = np.zeros(10)

arr[4] = 1

print(arr)

In [ ]:
arr = np.array([1,2,0,0,4,0])

rev = arr[::-1]

print(rev)

In [ ]:
arr = np.ones((5,5))

arr[1:-1,1:-1] = 0

print(arr)

Array Operations

In [9]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [10]:
print(x + y)
print(x - y)
print(x * y)
print(x**2)

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 5 12]
 [21 40]]
[[ 1  4]
 [ 9 25]]


In [11]:
print(np.dot(v,w))

219


In [12]:
print(np.dot(x,v))

[29 77]


In [13]:
print(np.dot(x,y))

[[19 22]
 [50 58]]


In [14]:
print(np.concatenate((x,y), axis=0))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [15]:
print(np.vstack((v,w)))

[[ 9 10]
 [11 12]]


In [ ]:
np.concatenate((x,v))
#Error because x is 2D and v is 1D, cannot concatenate along axis 0.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Matrix Operations

In [17]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [18]:
A_inv = np.linalg.inv(A)

result = np.dot(A, A_inv)

print(result)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [19]:
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB =")
print(AB)

print("BA =")
print(BA)

AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]


In [20]:
left = np.transpose(np.dot(A,B))

right = np.dot(np.transpose(B), np.transpose(A))

print(left)
print(right)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


Experiment: How Fast is NumPy

Element-wise Addition

In [21]:
import numpy as np
import time

In [22]:
size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()

result = [list1[i] + list2[i] for i in range(size)]

end = time.time()

print("Python list addition time:", end-start)

Python list addition time: 0.07092881202697754


In [23]:
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()

result = arr1 + arr2

end = time.time()

print("NumPy addition time:", end-start)

NumPy addition time: 0.01341700553894043


Element-wise Multiplication

In [24]:
start = time.time()

result = [list1[i] * list2[i] for i in range(size)]

end = time.time()

print("Python multiplication time:", end-start)

Python multiplication time: 0.08837103843688965


In [25]:
start = time.time()

result = arr1 * arr2

end = time.time()

print("NumPy multiplication time:", end-start)

NumPy multiplication time: 0.013505935668945312


Dot Product

In [26]:
start = time.time()

dot = np.dot(arr1,arr2)

end = time.time()

print("NumPy dot product time:", end-start)

NumPy dot product time: 0.0015981197357177734


In [27]:
start = time.time()

dot = sum(list1[i] * list2[i] for i in range(size))

end = time.time()

print("Python dot product time:", end-start)

Python dot product time: 0.05775332450866699


Matrix Multiplication

In [28]:
size = 100

A = [[1]*size for _ in range(size)]
B = [[1]*size for _ in range(size)]

start = time.time()

C = [[sum(A[i][k]*B[k][j] for k in range(size)) for j in range(size)] for i in range(size)]

end = time.time()

print("Python matrix multiplication:", end-start)

Python matrix multiplication: 0.050623416900634766


In [29]:
A = np.ones((1000,1000))
B = np.ones((1000,1000))

start = time.time()

C = np.dot(A,B)

end = time.time()

print("NumPy matrix multiplication:", end-start)

NumPy matrix multiplication: 0.010632991790771484
